apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nationalparks1
  namespace: scsk-cd-dev
  labels:
    app: nationalparks1
    app.kubernetes.io/component: nationalparks1
    app.kubernetes.io/instance: nationalparks1
    app.kubernetes.io/name: nationalparks1
    app.kubernetes.io/part-of: nationalparks-git-app1
spec:
  to:
    kind: Service
    name: nationalparks1
  port:
    targetPort: 8080
